spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      # never data.sql wird nicht ausgeführt
      mode: always
      platform: dev

web:
  cors:
    allowed-origins: "http://localhost:4200"
