
server:
  ssl:
    enabled: true
    # keystore format
    key-store-type: PKCS12
    # keystore location
    key-store: classpath:keystore/springboot_letsencrypt.p12
    # keystore password
    key-store-password: fotoolpassword
    # SSL protocol to use
    protocol: TLS
    # Enabled SSL protocols
    enabled-protocols: TLSv1.2

spring:
  datasource:
    url: jdbc:h2:file:./fotool/db/ProdDataBase
  h2:
    console:
      enabled: false
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
      platform: prod
